# Array Attributes

In [2]:
import numpy as np

In [10]:
arr = np.array([2,3,4,])
arr

array([2, 3, 4])

In [11]:
a=[23,2344,"sdfa"]
a

[23, 2344, 'sdfa']

In [29]:
np.array(a)

array(['23', '2344', 'sdfa'], dtype='<U21')

In [35]:
arr =  np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.random.rand(6)  #normalisation

array([0.29667675, 0.67043285, 0.01887545, 0.27829078, 0.39973851,
       0.41400169])

In [15]:
np.random.randn(6)  #standardization

array([ 0.95136679,  0.01184881,  1.19720366,  0.14313187, -0.37308077,
       -0.8985516 ])

In [21]:
np.random.randint(6)

5

In [28]:
np.random.randint(2,6,3)

array([2, 4, 3], dtype=int32)

In [66]:
np.arange(1,20,3)  #return array with range of elements given

array([ 1,  4,  7, 10, 13, 16, 19])

In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.shape #return the order of matrix

(3, 3)

In [42]:
arr.size  #returns no. of elements in matrix/2d array

9

In [44]:
arr.dtype  #return datatype of elements of array

dtype('int64')

# Array Methods

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr.min()

np.int64(1)

In [48]:
arr.max()

np.int64(9)

In [49]:
arr.sum()

np.int64(45)

In [54]:
np.sum(arr,axis=0)  #sum of elements of matrix columnwise

array([12, 15, 18])

In [55]:
np.sum(arr,axis=1)  #sum of elements of matrix rowwise

array([ 6, 15, 24])

In [61]:
arr.mean()  #return mean of elements of elements matrix

np.float64(5.0)

In [58]:
arr.std()  #return standard deviation of elements of matrix

np.float64(2.581988897471611)

In [62]:
arr.argmax()  #return index of max element of matrix

np.int64(8)

In [63]:
arr.argmin()  #return index of min element of matrix

np.int64(0)

# Reshaping and Resizing

In [68]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [71]:
arr = arr.reshape(6,5)  #reshapes the elements of array in accordance of order of matrix
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])