In [1]:
import numpy as n

### Array indexing

In [2]:
arr = n.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr[1]  #Array's indexing works same as String's

np.int64(2)

### Array slicing

In [4]:
arr=n.arange(2,45)  #Array's slicing also same as String's

In [5]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44])

In [6]:
arr[2:19]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[::]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44])

In [8]:
arr[2:34:3]

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34])

### NumPy Indexing and Slicing of Matrix

In [9]:
arr = n.arange(1,31).reshape(6,5)

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [12]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [13]:
slice = arr[2:4,1:4]
slice
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Boolean Indexing

In [25]:
arr = n.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [34]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])