In [1]:
import numpy as n

### **Array Operations**

#### Arithmetic Operations

In [11]:
a1 = n.arange(1,6)
a2=n.array([6,7,9,10,23])

a1,a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  9, 10, 23]))

In [15]:
a1+a2  #adds up the elements of array one by one but size of array and type of array elements should be same

array([ 7,  9, 12, 14, 28])

In [16]:
a1-a2

array([ -5,  -5,  -6,  -6, -18])

In [17]:
a1*a2

array([  6,  14,  27,  40, 115])

In [18]:
a1/a2

array([0.16666667, 0.28571429, 0.33333333, 0.4       , 0.2173913 ])

In [19]:
a1//a2

array([0, 0, 0, 0, 0])

In [20]:
a2//a1

array([6, 3, 3, 2, 4])

In [25]:
a1**a2

array([                1,               128,             19683,
                 1048576, 11920928955078125])

Also works same for matrix

#### Broadcasting

In [22]:
a1

array([1, 2, 3, 4, 5])

In [24]:
a1+10

array([11, 12, 13, 14, 15])

Works for every arithmetic operation

#### Deep and Shallow copy

Deep copy is concept in which after slicing an array the values of array also changes

But in shallow copy array does not changes while slicing it

In [67]:
a=n.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [68]:
slice = a[:6]
slice = slice*10
slice

array([10, 20, 30, 40, 50, 60])

In [69]:
a  #There is no change in array while we have performed broadcasting on slice

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

But after assigning array to new variable if we make any changes in variable then array also changes

In [77]:
# b=a
# b[0]=23
# b

In [78]:
# array([ 23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#      18, 19, 20, 21, 22, 23, 24, 25])

For preventing this deep copy we use:

In [79]:
b=a.copy()

In [80]:
b[0]=23


In [81]:
b

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

#### Matrix Operations

In [83]:
mat1=n.array([[1,2],[3,4]])
mat2=n.array([[5,6],[7,8]])

In [84]:
mat1

array([[1, 2],
       [3, 4]])

In [85]:
mat2

array([[5, 6],
       [7, 8]])

In [87]:
mul = mat1 @ mat2  #it is way to multiply matrix
mul

array([[19, 22],
       [43, 50]])

In [88]:
mul2 = n.dot(mat1,mat2)  #Does the same thing
mul2

array([[19, 22],
       [43, 50]])

In [90]:
trans = mat1.T  #Transposes the matrix
trans

array([[1, 3],
       [2, 4]])

### **Advance Array Manipulation**

#### Stacking Array

In Advance array manipulation operation can only be performed on vectors not matrices

In [94]:
a = n.array([1,2,3,4,5])
b = n.array([6,7,8,9,10])

In [97]:
n.vstack((a,b))  #Vertically stacks the array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [98]:
n.hstack((a,b))  #Horizontally stacks the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
n.column_stack((a,b))  #changes the row to column of every array

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### Splitting Array

In [101]:
c = n.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
n.hsplit(c,2)  #Splits array in parts horizontally but the number of parts should be factor of number of columns

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [104]:
n.vsplit(c,4)  #Splits array in parts vertically but the number of parts should be factor of number of rows

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]