In [2]:
import numpy as np

**Attribute Based Questions**

In [96]:
# Create a 1D NumPy array of numbers from 0 to 9
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# Write a code to convert a 1D array to a 2D array with 2 rows.
# Given:
arr = np.arange(6)

arr = arr.reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
# Print the following attributes of the array:
# The shape of the array.
# The number of array dimensions.
# The size of each element in bytes.
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print(f"The shape of the array is: {my_array.shape}")
print(f"The number of array dimensions is: {my_array.ndim}")
print(f"The size of each element in bytes is: {my_array.itemsize}")

The shape of the array is: (4, 2)
The number of array dimensions is: 2
The size of each element in bytes is: 2


In [104]:
# Create a 3×3 NumPy array of all True
arr = np.ones((3,3),dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [107]:
# Extract the documentation of NumPy’s arange() function
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [110]:
# Create a 1D array filled with zeros and another filled with ones
zeros = np.zeros(5)
ones = np.ones(5)
zeros,ones

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [114]:
# Create a 1D array of 10 evenly spaced values between 5 and 50
np.linspace(5,50,10)


array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [115]:
# Convert a Python list into a NumPy array
# Given:
py_list = [1, 2, 3, 4, 5]

arr = np.array(py_list)
arr

array([1, 2, 3, 4, 5])

In [120]:
# Find the memory size of a NumPy array of numbers from 0 to 9
arr = np.arange(10)
arr.nbytes

80

In [125]:
# Reverse a 1D NumPy array
# Given:
arr = np.arange(10)

arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Valid Sudoku**

In [19]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [20]:
r_sum = np.sum(s,axis=1)
for i in r_sum:
    if i!=45:
        print("Sudoku is not valid")
        break
else:
   print("Sudoku is valid for rows")


Sudoku is valid for rows


In [21]:
c_sum = np.sum(s,axis=0)
for j in c_sum:
      if j!=45:
          print("Sudoku is not valid")
          break
else:
        print("Sudoku valid for columns")

Sudoku valid for columns


In [22]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        if n.sum()!=45:
            print("Sudoku is not Valid")
            break
    else:
        print("Sudoku is Valid")
        break


Sudoku is Valid


**General Questions**

In [82]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [83]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [84]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [85]:
#Extract Math marks of all students.
math = data[:,1]
math

array([85, 92, 76, 65, 90])

In [86]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [87]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]


array([[19, 92, 88]])

In [88]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [89]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])


3

In [90]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [91]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [92]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [93]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])